# Generated by Django 4.2.11 on 2024-04-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('review', models.TextField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='barber',
            name='reviews',
            field=models.ManyToManyField(to='main_app.review'),
        ),
    ]
