# Generated by Django 4.2.11 on 2024-05-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_review_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='barber_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.barber'),
            preserve_default=False,
        ),
    ]
