# Generated by Django 4.2.11 on 2024-05-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_review_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='reviews',
            field=models.ManyToManyField(related_name='barbers_reviews', to='main_app.review'),
        ),
    ]
